Add RuboCop RSpec support
test-prof/test-prof pull request #199
Opened 2020-11-09 09:21 UTC by pirj

### What is the purpose of this pull request?

Previously, RuboCop RSpec failed to detect RSpec aliases. A number of
cops were failing false offences, and some cops were unable to lint, as
they were skipping locally defined RSpec aliases taking them for
arbitrary blocks and method calls.

See:
 - rubocop-hq/rubocop-rspec#1077
 - rubocop-hq/rubocop-rspec#956

Sibling pull requests:
 - https://github.com/palkan/action_policy/pull/138

`Gemfile`:
```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rubocop-rspec'
gem 'test-prof', path: '../../test-prof'
```

`.rubocop.yml`:
```yaml
require:
  - rubocop-rspec

inherit_gem:
  test-prof: .rubocop-rspec-aliases.yml
```

`spec/o_spec.rb`:
```ruby
# frozen_string_literal: true

RSpec.describe 'O' do
  let_it_be(:x) { 'the_one_and_only' }

  # I must come above any other memoized helper! (disclaimer: due to an arguable default linter setting)
  subject(:o) { 'everchanging' } # Not really everchanging with a frozen_string_literal

  it { expect(o).not_to eq("#{x}#{x}") }
end
```

### What changes did you make? (overview)

 - added an RSpec alias config file that RuboCop is able to load and append to the default RuboCop RSpec alias configuration.
 - added docs on how to tell RuboCop to use those aliases

### Is there anything you'd like reviewers to focus on?

Should I through in some test to make sure the detection works as expected?

I don't have a project that uses `let_it_be`/`before_all` handy at the moment.
Do you mind to checking this against a live project?

### Checklist

- [-] I've added tests for this change
- [x] I've added a Changelog entry
- [x] I've updated a documentation

2020-11-09 09:33 UTC, pirj commented
Liche fail seems unrelated:
```
 docs/profilers/factory_prof.md
	ERROR	http://www.brendangregg.com/flamegraphs.html
Error: 		Dial tcp4 <nil>->50.63.8.6:80: i/o timeout
Error: Process completed with exit code 1.
```

2020-11-17 11:34 UTC, palkan requested changes
👍 

Same here: can we move the config to `config/rubocop-rspec.yml`?

2020-11-17 19:55 UTC, pirj commented
Moved the config and tested again, works.

2020-11-18 12:18 UTC, palkan commented on test-prof.gemspec
> +  spec.files = Dir.glob("lib/**/*") + Dir.glob("config/**/*") + Dir.glob("assets/**/*") + %w[README.md LICENSE.txt CHANGELOG.md] + %w[config/rubocop-rspec.yml]
`config/**/*` is already included
```suggestion
  spec.files = Dir.glob("lib/**/*") + Dir.glob("config/**/*") + Dir.glob("assets/**/*") + %w[README.md LICENSE.txt CHANGELOG.md]
```

2020-11-18 16:15 UTC, pirj commented on test-prof.gemspec
> +  spec.files = Dir.glob("lib/**/*") + Dir.glob("config/**/*") + Dir.glob("assets/**/*") + %w[README.md LICENSE.txt CHANGELOG.md] + %w[config/rubocop-rspec.yml]
Thanks! I've missed that completely.

2020-11-18 17:03 UTC, merged

2020-11-18 17:03 UTC, palkan commented
Thanks!