Fix/escaped single quote
test-prof/test-prof pull request #314
Opened 2024-12-05 20:46 UTC by elasticspoon

Related to https://github.com/test-prof/test-prof/issues/313

This is a PR with some changes to the rstamp_tests to more closely reflect reality and a test case to illustrate the behavior in this issue.

### Test Changes

When RStamp reads in files it uses `File.readlines` which results in array of strings ending in newlines:

```rb
# somefile.rb
puts 'foo'
puts 'bar'

# somewhere else
File.readlines('somefile.rb')
=> ["puts 'foo'\n", "puts 'bar'\n"]
```

Meanwhile in the tests we take a heredoc and split it along the newline:

```rb
let(:source) do
  <<~CODE
    it "doesn't do what it should do" do
      expect(subject.body).to eq("OK")
    end
  CODE
end

let(:code) { source.split("\n") }

code
=> ["it \"doesn't do what it should do\" do", "expect(subject.body).to eq(\"OK\")", "end"]
```

This means that the code inputs do not have trailing newlines. It does not matter with the current test cases BUT with those changes the following added test case fails.

```rb
context "with escaped single quotes" do
  let(:source) do
    <<~code
      it 'has a \\' in the description' do # with comment
        expect(subject.body).to eq("not found")
      end
    code
  end

  let(:expected) do
    <<~code
      it "has a in the description", :todo do # with comment
        expect(subject.body).to eq("not found")
      end
    code
  end

  specify do
    is_expected.to eq 0
    expect(code.join).to eq expected
  end
end
```

### Failing Test Case

The reason the test case fails is the following code

```rb
# lib/test_prof/rspec_stamp.rb
def stamp_example(example, tags)
  # ...
  replacement = "\\1#{parsed.fname}#{need_parens ? "(" : " "}" \
                "#{[desc, tags_str, htags_str].compact.join(", ")}" \
                "#{need_parens ? ") " : " "}\\3"
  # replacement => "\\1it \"has a \\' in the description\", :todo \\3"

  # EXAMPLE_RXP = /(\s*)(\w+\s*(?:.*)\s*)(do|{)/.freeze
  example.sub!(EXAMPLE_RXP, replacement)
```

In this case the `\\1` and `\\3` will get replacement with their respective match groups, but the `\'` got escaped in such a way that is has turned into a match group. `$'` is a global variable that holds the match group for the string after the match [(see here)](https://docs.ruby-lang.org/en/2.2.0/Regexp.html#class-Regexp-label-Special+global+variables). So anything after `do` or `{` could be replaced there, except only in this case is it valid syntax.

### Fixing

I am not sure what the best fix is but I feel it would be something revolving around not modifying the strings in the `stamp_example` function and instead building up a replacement string and passing it back. However, I am unsure if this edge case merits the rework and if there was some other reason that the string were modified in place.

I do find the modification of strings in place to be pretty surprising.

2024-12-06 22:41 UTC, palkan requested changes
Thanks for the fix!

Could you please take a look at the failing spec?

2024-12-12 04:06 UTC, elasticspoon commented
> Thanks for the fix!
> 
> Could you please take a look at the failing spec?

Sorry for the confusion. I did not actually implement the fix just made a failing spec to demonstrate the issue. I'm down to do it tho. 

Only question I had is: the code mutates an array of strings when it does the replacements. Should I keep it that way or can I return new strings instead?

2024-12-13 00:33 UTC, palkan commented
> I did not actually implement the fix just made a failing spec to demonstrate the issue. I'm down to do it tho.

Ah, got it.

> the code mutates an array of strings when it does the replacements. Should I keep it that way or can I return new strings instead?

I don't remember why it has been implemented this way (I believe, this code stayed as is since the very first version back from 2017). Creating new strings would require quite a refactoring.

I wonder if instead we can: 1) get rid of `\\<n>` substitutes and use, for example,`example.gsub!(regexp) do ... end` to replace parts; 2) add some escaping, so we don't accidentally introduce  replacements.

2024-12-30 04:48 UTC, elasticspoon commented
> 1) get rid of `\\<n>` substitutes and use, for example,`example.gsub!(regexp) do ... end` to replace parts

That approach works nicely.

> 2) add some escaping, so we don't accidentally introduce replacements.

Not 100% sure what you would like to escape. Or was that meant as a alternative option to 1?

2025-01-03 01:56 UTC, palkan commented
> Not 100% sure what you would like to escape. Or was that meant as a alternative option to 1?

Yeah, that was an alternative idea. Nvm, the current implementation looks good 👍 Thanks!

2025-01-03 01:56 UTC, merged